//
//  LoginViewController.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 21/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ModularFoundation

protocol LoginViewControllerViewControllerInput
{
  func displaySomething(viewModel: LoginViewController)
}

protocol LoginViewControllerViewControllerOutput
{
  func doSomething(request: LoginViewController)
}

class LoginViewControllerViewController: UIViewController, LoginViewControllerViewControllerInput
{
    // MARK: - Member variables

    var output: LoginViewControllerViewControllerOutput!
    var router: LoginViewControllerRouter!
    var base: BaseViewController!

    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
      super.awakeFromNib()
      LoginViewControllerConfigurator.sharedInstance.configure(viewController: self)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad()
    {
      super.viewDidLoad()
      doSomethingOnLoad()
    }
    
    // MARK: - Event handling
    
    func doSomethingOnLoad()
    {
      // NOTE: Ask the Interactor to do some work
      
      let request = LoginViewController()
      output.doSomething(request: request)
    }
    
    // MARK: - Display logic
    
    func displaySomething(viewModel: LoginViewController)
    {
      // NOTE: Display the result from the Presenter
      
      // nameTextField.text = viewModel.name
    }
}
