//
//  ProspectusViewController.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProspectusViewControllerInput
{
    
}

protocol ProspectusViewControllerOutput
{
    func getProspectcLists(token: String?)
}

class ProspectusViewController: UIViewController, ProspectusViewControllerInput
{
    // MARK: - Member variables
    var token: String!
    var output: ProspectusViewControllerOutput!
    var router: ProspectusRouter!
    var base: BaseViewController!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ProspectusConfigurator.sharedInstance.configure(viewController: self)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        getProspectcListsOnLoad()
        
    }
    
    func getProspectcListsOnLoad() {
        self.output.getProspectcLists(token: self.token)
    }
    
    // MARK: - Event handling
    
}
