//
//  ProspectusViewController.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SVProgressHUD

protocol ProspectusViewControllerInput
{
    func displayProspectsList(prospects: [Prospectus])
    func displayError(error: String)
}

protocol ProspectusViewControllerOutput
{
    func getProspectsLists(token: String?)
}

class ProspectusViewController: UIViewController, ProspectusViewControllerInput
{
    // MARK: - Member variables
    var token: String!
    var prospects: [Prospectus]?
    var output: ProspectusViewControllerOutput!
    var router: ProspectusRouter!
    
    // MARK: IBOutlet
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Object lifecycle
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ProspectusConfigurator.sharedInstance.configure(viewController: self)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        getProspectsListsOnLoad()
        tableView.tableFooterView = UIView(frame: .zero)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true);
        navigationController?.navigationBar.isHidden = true

    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Event handling
    func getProspectsListsOnLoad() {
        SVProgressHUD.show(withStatus: "Cargando")
        self.output.getProspectsLists(token: self.token)
    }
    
    // MARK: - Display logic
    func displayError(error: String) {
        SVProgressHUD.dismiss()
        let alert = UIAlertController(title: "Alerta", message: error, preferredStyle: UIAlertControllerStyle.alert)
        alert.addAction(UIAlertAction(title: "Aceptar", style: UIAlertActionStyle.default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
    
    func displayProspectsList(prospects: [Prospectus]) {
        SVProgressHUD.dismiss()
        self.prospects = prospects
       // saveUserDefaut(prospects: self.prospects!)
        self.tableView.reloadData()
    }
    
    func saveUserDefaut(prospects: [Prospectus]){
        let prospectData = NSKeyedArchiver.archivedData(withRootObject: prospects)
        let userDefaults = UserDefaults.standard
        userDefaults.set(prospectData, forKey: "prospects")
    }
   
    @IBAction func logoutButtom(_ sender: Any) {
        SVProgressHUD.show(withStatus: "Cerrando sesión")
        self.router.logout()
    }
}

extension ProspectusViewController:  UITableViewDataSource, UITableViewDelegate
{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if let prospects = self.prospects {
            return prospects.count
        } else {
            return 0
        }
    }
    
    public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "prospectusCell") as! ProspectusCell
        cell.prospectus = self.prospects?[indexPath.row]
        cell.router = self.router
        cell.token = self.token
        return cell
    }
  
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
}

