//
//  LoginPresenter.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 21/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation
import UIKit

protocol LoginPresenterInput {
    func presentMessage(_ message: String)
    func presentDashBoard(_ token: String)
}

protocol LoginPresenterOutput {
    func showMessage(_ message: String)
    func goToDashBoard(_ token : String?)
}

class LoginPresenter : LoginPresenterInput {
    
    var output: LoginPresenterOutput!
    
    func presentMessage(_ message: String) {
        self.output.showMessage(message)
    }
    
    func presentDashBoard(_ token: String) {
        self.output.goToDashBoard(token)
    }
}
