//
//  LoginPresenter.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 21/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginPresenterPresenterInput
{
  func presentSomething(response: LoginPresenter)
}

protocol LoginPresenterPresenterOutput: class
{
  func displaySomething(viewModel: LoginPresenter)
}

class LoginPresenterPresenter: LoginPresenterPresenterInput
{
  weak var output: LoginPresenterPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: LoginPresenter)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = LoginPresenter()
    output.displaySomething(viewModel: viewModel)
  }
}
