//
//  ProspectusPresenter.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProspectusPresenterInput
{
  
}

protocol ProspectusPresenterOutput: class
{
  
}

class ProspectusPresenter: ProspectusPresenterInput
{
  weak var output: ProspectusPresenterOutput!
  
  // MARK: - Presentation logic
  
}
