//
//  ProspectusPresenter.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProspectusPresenterInput
{
    func presentProspectsList(prospects: [Prospectus])
    func presentError(error: String)
}

protocol ProspectusPresenterOutput: class
{
    func displayProspectsList(prospects: [Prospectus])
    func displayError(error: String)
}

class ProspectusPresenter: ProspectusPresenterInput
{
  weak var output: ProspectusPresenterOutput!
  
  // MARK: - Presentation logic
    func presentProspectsList(prospects: [Prospectus]) {
        self.output.displayProspectsList(prospects: prospects)
    }
    
    func presentError(error: String) {
        self.output.displayError(error: error)
    }
}
