//
//  Prospectus.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// NOTE: Domain Model

class Prospectus: Equatable
{
    var name: String?
    var lastName: String?
    var identification: String?
    var phone: String?
    var statusCode: Int?
    
    init(){}
    
    init(name: String?, lastName: String?, identification: String?, phone: String?, statusCode: Int?) {
        self.name = name
        self.lastName = lastName
        self.identification = identification
        self.phone = phone
        self.statusCode = statusCode
    }
    
    public static func ==(lhs: Prospectus, rhs: Prospectus) -> Bool {
        return lhs.name == rhs.name &&
            lhs.lastName == rhs.lastName &&
            lhs.identification == rhs.identification &&
            lhs.phone == rhs.phone &&
            lhs.statusCode == rhs.statusCode
    }
}



