//
//  ProspectusConfigurator.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, BusinessLogic, and Presenter

extension ProspectusConfiguratorViewController: ProspectusConfiguratorPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ProspectusConfiguratorBusinessLogic: ProspectusConfiguratorViewControllerOutput
{
}

extension ProspectusConfiguratorPresenter: ProspectusConfiguratorBusinessLogicOutput
{
}

class ProspectusConfiguratorConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ProspectusConfiguratorConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ProspectusConfiguratorViewController)
  {
    let router = ProspectusConfiguratorRouter()
    router.viewController = viewController
    
    let presenter = ProspectusConfiguratorPresenter()
    presenter.output = viewController
    
    let interactor = ProspectusConfiguratorBusinessLogic()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
