//
//  ProspectusConfigurator.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díazon 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, BusinessLogic, and Presenter

extension ProspectusViewController: ProspectusPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ProspectusBusinessLogic: ProspectusViewControllerOutput
{
}

extension ProspectusPresenter: ProspectusBusinessLogicOutput
{
}

class ProspectusConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ProspectusConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ProspectusViewController)
  {
    let router = ProspectusRouter()
    router.viewController = viewController
    
    let presenter = ProspectusPresenter()
    presenter.output = viewController
    
    let interactor = ProspectusBusinessLogic()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
