//
//  LoginRouter.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 21/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginRouterInput
{
    func goToDashboard()
}

class LoginRouter: LoginRouterInput
{
    weak var viewController: LoginViewController!
    var prospectusViewController : ProspectusViewController!
    // segueToProspectus
    // MARK: - Navigation
    
    func goToDashboard()
    {
        viewController.performSegue(withIdentifier: "segueToProspectus", sender: nil)
        
    }
    
    // MARK: - Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with
        
        if segue.identifier == "segueToProspectus" {
            passDataToProspectusScene(segue: segue)
        }
    }
    
    func passDataToProspectusScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router how to pass data to the next scene
        self.prospectusViewController = segue.destination as! ProspectusViewController
        self.prospectusViewController.token = self.viewController.jsonString
    }
}
