//
//  ProspectusRouter.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProspectusRouterInput
{
    func goToEdit(prospectus: Prospectus)
}

class ProspectusRouter: ProspectusRouterInput
{
    weak var viewController: ProspectusViewController!
    var editViewController : EditViewController!
    var prospectus: Prospectus?
    
    // MARK: - Navigation
    func goToEdit(prospectus: Prospectus)
    {
        self.prospectus = prospectus
        viewController.performSegue(withIdentifier: "segueToEdit", sender: nil)
    }
    
    // MARK: - Communication
    func passDataToNextScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with
        
        if segue.identifier == "segueToEdit" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    func passDataToSomewhereScene(segue: UIStoryboardSegue)
    {
        self.editViewController = segue.destination as! EditViewController
        self.editViewController.prospectus = self.prospectus!
    }
}
