//
//  LoginBusinessLogic.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 21/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogicInput
{
    func loginUser(user: User?)
}

protocol LoginBusinessLogicOutput
{
    func presentMessage(_ message: String)
    func presentDashBoard(_ json: String)
}

class LoginBusinessLogic: LoginBusinessLogicInput
{
    var output: LoginBusinessLogicOutput!
    var repositoryLocator = RepositoryLocator().securityRepository()
    
    // MARK: - Business logic
    
    func loginUser(user: User?) {
        //let userDTO = MapperModel.convertToUserDTO(user: user!)
        repositoryLocator.loginUser(user!) { (json, error) in
            if (json != nil && json != "" )  {
                self.output.presentDashBoard(json!)
            }else {
                let errorString = "error servicio"
                self.output.presentMessage(errorString)
            }
        }
    }
}
