//
//  ProspectusBusinessLogic.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProspectusBusinessLogicInput
{
    func getProspectsLists(token: String?)
}

protocol ProspectusBusinessLogicOutput
{
    func presentProspectsList(prospects: [Prospectus])
    func presentError(error: String)
}

class ProspectusBusinessLogic: ProspectusBusinessLogicInput
{
    var output: ProspectusBusinessLogicOutput!
    var repositoryLocator = RepositoryLocator().prospectusRepository()
    
    func getProspectsLists(token: String?) {
        repositoryLocator.getProspectsLists(token!) { ( prospectsDTO, error) in
            if error == nil  {
                let prospects = MapperModel.convertProspectusDTOToProspectus(prospectsDTO: prospectsDTO!)
                self.output.presentProspectsList(prospects: prospects)
            } else {
                let errorString = "no se pudo cargar el servicio"
                self.output.presentError(error: errorString)
            }
        }
    }
    // MARK: - Business logic
    
}
