//
//  ProspectusBusinessLogic.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProspectusBusinessLogicBusinessLogicInput
{
  func doSomething(request: ProspectusBusinessLogic)
}

protocol ProspectusBusinessLogicBusinessLogicOutput
{
  func presentSomething(response: ProspectusBusinessLogic)
}

class ProspectusBusinessLogicBusinessLogic: ProspectusBusinessLogicBusinessLogicInput
{
  var output: ProspectusBusinessLogicBusinessLogicOutput!
  var repositoryLocator = RepositoryLocator().securityRepository()
  
  // MARK: - Business logic
  
  func doSomething(request: ProspectusBusinessLogic)
  {
    // NOTE: Use some repository to do the work
    
    // repositoryLocator.doSomeWork()

    // Map DTO response from repository to Domain model entity
    // let dtoResponse = MapperModel.convertToProspectusBusinessLogic(dto: ProspectusBusinessLogicDTO)

    // NOTE: Pass the result to the Presenter
    
    let response = ProspectusBusinessLogic()
    output.presentSomething(response: response)
  }
}
