//
//  ProspectusDTO.swift
//  Aktif-DirectSellingSAS
//
//  Created by Esteban Caro on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import ObjectMapper

// NOTE: DTO Model

class ProspectusDTODTO : Mappable {
    var AtributeOne: Int?
    var AtributeTwo: String?

    required init?(map: Map){
        
    }
    
    init(){}

    func mapping(map: Map) {
        AtributeOne <- map["atributeOne"]
        AtributeTwo <- map["atributeTwo"]
    }

}



