//
//  ProspectusDTO.swift
//  Aktif-DirectSellingSAS
//
//  Created by Mateo Gutiérrez Díaz on 22/11/17.
//  Copyright (c) 2017 Mateo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation
import ObjectMapper

// NOTE: DTO Model

class ProspectusDTO : Mappable {
    var name: String?
    var lastName: String?
    var identification: String?
    var phone: String?
    var statusCode: Int?
    
    required init?(map: Map){}
    init(){}
    
    init(name: String?, lastName: String?, identification: String?, phone: String?, statusCode: Int?) {
        self.name = name
        self.lastName = lastName
        self.identification = identification
        self.phone = phone
        self.statusCode = statusCode
    }
    
    func mapping(map: Map) {
        name <- map["name"]
        lastName <- map["surname"]
        identification <- map["schProspectIdentification"]
        phone <- map["telephone"]
        statusCode <- map["statusCd"]
    }
}



